#!/bin/bash
set -x
unset MFX_HOME
cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_DISPATCHER=OFF -DBUILD_SAMPLES=OFF -DENABLE_TEXTLOG=ON -DENABLE_STAT=ON ..  
#cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_DISPATCHER=OFF -DBUILD_SAMPLES=OFF .. 
make -j$(nproc) 
#sudo make install
