set -x
cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_DISPATCHER=OFF -DBUILD_SAMPLES=OFF -DENABLE_TEXTLOG=OFF .. 
#cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_DISPATCHER=OFF -DBUILD_SAMPLES=OFF .. 
make -j$(nproc) 
